---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9999/test
    username: root
    password: root

  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080
  max-http-header-size: 10000000
  tomcat:
    max-http-form-post-size: 929145600

logging:
  level: debug